services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
      - nextcache:/app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: >
      sh -c "node .yarn/releases/yarn-4.17.1.cjs install && node .yarn/releases/yarn-4.17.1.cjs dev"

volumes:
  nodemodules:
  nextcache:
